### ISSUE TITLE
Fetching CSS does not complete

### ISSUE THREAD

**Issue by edtalmadge** [Zignd/HTML-CSS-Class-Completion#4]
Great plugin.

I tried using it on a folder containing hundreds of CSS files.

A message appears stating:
"HTML CSS Class Completion: Fetching CSS rules from CSS files, please wait."

The message never goes away.
The CSS intellisense does not function.

**Comment by Zignd** [comment]
You're right, the message never goes away, but what actually happens is that after some seconds, or maybe minutes, depending on how big is your project, another message pops up stating that the fetching process have finished.

Also, I've just ran some tests with the plugin on the latest VS Code version and it's working.

**Comment by edtalmadge** [comment]
Sounds great.

I left VS Code open overnight. The "Fetching CSS rules from CSS files, please wait" message is still there. But, the CSS intellisense does not seem to be running yet.

How does the CSS intellisense normally work? Should I place my cursor between the quotes in class="" and just start typing?
Or, should I place my cursor between the quotes in class="" and press control + space?

**Comment by Howshall** [comment]
Agree that while v0.0.2 extension is working normally for some of my 'normal' production HTML (So extension initially displays 'Fetching CSS rules from CSS files, please wait.' VSCode notification, then after a short while 2nd 'Finished fetching CSS rules from CSS files.' VSCode - See attached screenshot for good behaviour reference)
![html css classes extension 2x notifications](https://cloud.githubusercontent.com/assets/13105488/15009958/7de02e5c-11e1-11e6-9052-df97ef8d1af3.jpg)

However for one of my more unusual production HTML pages which has 1x External Internet CSS file + mostly inline CSS rules I can re-produce this error of v0.0.2 never displaying 2nd 'Finished...' message and never enabling CSS class completion within that page.

Now in terms of inline CSS styles I know that's currently a [Not implemented yet] feature clearly stated on project homepage, so I guess it must be the external CSS Internet URL that must be confusing/breaking the extension completing atm?

Hopefully the attached cut down '[index - Copy.html](https://github.com/Zignd/HTML-CSS-Class-Completion/files/248459/index.-.Copy.txt)' (had to change it's extension to .txt to allow upload) I'm attaching will assist @Zignd debug this issue and further improve this extension :-)

**Comment by prep4gmat** [comment]
+1

**Comment by daniloar** [comment]
+1

**Comment by anuragd7** [comment]
+1

**Comment by Tinee** [comment]
+1

**Comment by dafonso** [comment]
+1

**Comment by levka9** [comment]
+1

**Comment by Zignd** [comment]
Would you guys mind testing it again? I suppose the issue is fixed now as I completely rewrote the extension and fixed some bugs on it, the newest release is already on the Marketplace. Thanks!

**Comment by Howshall** [comment]
Confirm that for both of previously tested projects new discrete bottom status bar messages + bottom left lightening icon now say that caching CSS rules have completed within expected shortish timescales.

![html css classes extension new status bar display](https://cloud.githubusercontent.com/assets/13105488/18441611/9a036488-7905-11e6-8f6f-8b2b514a1875.jpg)

Note extension still doesn't read/cache Internet hosted, or inline specified CSS rules, so you should only expect CSS class completion for CSS styles that are in locally linked external .css files atm.

Congrats @Zignd on much more subtle notifications and now no longer needing to click to dismiss messages that would otherwise block screenspace 👍
